In [1]:
import pandas as pd
data = pd.read_csv("wine.csv")
data.head()

wine.class  Alcohol  MalicAcid   Ash  AlcAsh   Mg  Phenols  Flav  \
0     barolo    14.23       1.71  2.43    15.6  127     2.80  3.06   
1     barolo    13.20       1.78  2.14    11.2  100     2.65  2.76   
2     barolo    13.16       2.36  2.67    18.6  101     2.80  3.24   
3     barolo    14.37       1.95  2.50    16.8  113     3.85  3.49   
4     barolo    13.24       2.59  2.87    21.0  118     2.80  2.69   

   NonFlavPhenols  Proa  Color   Hue    OD  Proline  
0            0.28  2.29   5.64  1.04  3.92     1065  
1            0.26  1.28   4.38  1.05  3.40     1050  
2            0.30  2.81   5.68  1.03  3.17     1185  
3            0.24  2.18   7.80  0.86  3.45     1480  
4            0.39  1.82   4.32  1.04  2.93      735

In [8]:
import numpy as np

np.set_printoptions(suppress = True)

x = data.drop("wine.class", axis = 1)
y = data["wine.class"]


Decision Tree before PCA

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, random_state = 50)

from sklearn.tree import DecisionTreeClassifier
dt_bef_pca = DecisionTreeClassifier().fit(x_train,y_train)



from sklearn.metrics import accuracy_score

#Accuracy on train data
print("Accuracy on train: ",accuracy_score(y_train, dt_bef_pca.predict(x_train)))

#Accuracy on Test data
print("Accuarcy on Test: ", accuracy_score(y_test, dt_bef_pca.predict(x_test)))

Accuracy on train:  1.0
Accuarcy on Test:  0.9259259259259259


Perform PCA

In [12]:
from sklearn.decomposition import PCA

pca = PCA(n_components=13).fit(x)

print(pca.explained_variance_ratio_, "\n")
print(pca.explained_variance_, "\n")
print(pca.components_, "\n")

[0.99809123 0.00173592 0.00009496 0.00005022 0.00001236 0.00000846
 0.00000281 0.00000152 0.00000113 0.00000072 0.00000038 0.00000021
 0.00000008] 

[99201.78951748   172.53526648     9.4381137      4.99117861
     1.22884523     0.84106387     0.27897352     0.15138127
     0.11209676     0.0717026      0.03757598     0.02107237
     0.0082037 ] 

[[ 0.00165926 -0.00068102  0.00019491 -0.0046713   0.01786801  0.00098983
   0.00156729 -0.00012309  0.00060061  0.00232714  0.00017138  0.00070493
   0.99982294]
 [ 0.00120341  0.00215498  0.00459369  0.02645039  0.99934419  0.00087796
  -0.00005185 -0.00135448  0.0050044   0.01510035 -0.00076267 -0.00349536
  -0.01777381]
 [-0.01687381 -0.12200337 -0.05198743 -0.938593    0.02978025  0.04048464
   0.08544334 -0.01351078  0.02465938 -0.29139846  0.02597766  0.07032397
  -0.00452868]
 [-0.14144678 -0.16038954  0.00977281  0.33096526  0.00539376  0.07458466
   0.16908672 -0.01080556  0.05012095 -0.87889369  0.06003494  0.17820025
   0.0031129

Perform Scaling

In [28]:
from sklearn.preprocessing import StandardScaler

x_sc = pd.DataFrame(StandardScaler().fit_transform(x) , columns=x.columns)

x_sc.head()

/Users/amit.panda03/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/Users/amit.panda03/anaconda3/lib/python3.7/site-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


Alcohol  MalicAcid       Ash    AlcAsh        Mg   Phenols      Flav  \
0  1.518613  -0.562250  0.232053 -1.169593  1.913905  0.808997  1.034819   
1  0.246290  -0.499413 -0.827996 -2.490847  0.018145  0.568648  0.733629   
2  0.196879   0.021231  1.109334 -0.268738  0.088358  0.808997  1.215533   
3  1.691550  -0.346811  0.487926 -0.809251  0.930918  2.491446  1.466525   
4  0.295700   0.227694  1.840403  0.451946  1.281985  0.808997  0.663351   

   NonFlavPhenols      Proa     Color       Hue        OD   Proline  
0       -0.659563  1.224884  0.251717  0.362177  1.847920  1.013009  
1       -0.820719 -0.544721 -0.293321  0.406051  1.113449  0.965242  
2       -0.498407  2.135968  0.269020  0.318304  0.788587  1.395148  
3       -0.981875  1.032155  1.186068 -0.427544  1.184071  2.334574  
4        0.226796  0.401404 -0.319276  0.362177  0.449601 -0.037874

Perform PCA on scaled Data

In [33]:
pca_sc = PCA().fit(x_sc)
pca_sc.explained_variance_ratio_

array([0.36198848, 0.1920749 , 0.11123631, 0.0706903 , 0.06563294,
       0.04935823, 0.04238679, 0.02680749, 0.02222153, 0.01930019,
       0.01736836, 0.01298233, 0.00795215])

In [18]:
pca_sc.components_

array([[ 0.1443294 , -0.24518758, -0.00205106, -0.23932041,  0.14199204,
         0.39466085,  0.4229343 , -0.2985331 ,  0.31342949, -0.0886167 ,
         0.29671456,  0.37616741,  0.28675223],
       [-0.48365155, -0.22493093, -0.31606881,  0.0105905 , -0.299634  ,
        -0.06503951,  0.00335981, -0.02877949, -0.03930172, -0.52999567,
         0.27923515,  0.16449619, -0.36490283],
       [-0.20738262,  0.08901289,  0.6262239 ,  0.61208035,  0.13075693,
         0.14617896,  0.1506819 ,  0.17036816,  0.14945431, -0.13730621,
         0.08522192,  0.16600459, -0.12674592],
       [-0.0178563 ,  0.53689028, -0.21417556,  0.06085941, -0.35179658,
         0.19806835,  0.15229479, -0.20330102,  0.39905653,  0.06592568,
        -0.42777141,  0.18412074, -0.23207086],
       [-0.26566365,  0.03521363, -0.14302547,  0.06610294,  0.72704851,
        -0.14931841, -0.10902584, -0.50070298,  0.13685982, -0.07643678,
        -0.17361452, -0.10116099, -0.1578688 ],
       [-0.21353865, -0.536813

In [19]:
print("Cumulative variance: ", np.cumsum(pca_sc.explained_variance_ratio_))

Cumulative variance:  [0.36198848 0.55406338 0.66529969 0.73598999 0.80162293 0.85098116
 0.89336795 0.92017544 0.94239698 0.96169717 0.97906553 0.99204785
 1.        ]


In [31]:
pca_sc.inverse_transform(x_sc)

array([[ 0.10311659, -0.63259387, -0.89404452, ...,  1.26792499,
         1.06390783,  0.04104144],
       [-0.06212961, -0.97786416, -0.38578848, ...,  1.68251833,
        -0.52717709,  1.43036143],
       [ 0.60785481, -0.07319998, -0.71806293, ...,  0.77892501,
         0.59891334, -1.04421272],
       ...,
       [ 0.02384417, -1.32473315,  0.34428264, ..., -1.7218468 ,
         0.73043867, -0.92931179],
       [ 0.30059399, -0.90639444,  1.12258929, ..., -2.27384877,
         0.41203241, -0.72803764],
       [-0.40083257, -1.0370521 ,  1.58637575, ..., -1.79177811,
         1.64545806, -1.084195  ]])

Consider only those components which accout for 95 % variation

In [39]:
x_reduced  = PCA(n_components=0.87).fit_transform(x_sc)
print(x_reduced.shape)
x_reduced_df = pd.DataFrame(x_reduced, columns = ["PCA"+ str(i) for i in range(1,x_reduced.shape[1]+1)])
x_reduced_df.head()


(178, 7)


PCA1      PCA2      PCA3      PCA4      PCA5      PCA6      PCA7
0  3.316751 -1.443463 -0.165739 -0.215631  0.693043 -0.223880  0.596427
1  2.209465  0.333393 -2.026457 -0.291358 -0.257655 -0.927120  0.053776
2  2.516740 -1.031151  0.982819  0.724902 -0.251033  0.549276  0.424205
3  3.757066 -2.756372 -0.176192  0.567983 -0.311842  0.114431 -0.383337
4  1.008908 -0.869831  2.026688 -0.409766  0.298458 -0.406520  0.444074

Build Decision Tree on PCA df

In [40]:
x_train, x_test, y_train, y_test = train_test_split(x_reduced_df , y , test_size = 0.3, random_state = 50)

dt_sc_pca = DecisionTreeClassifier().fit(x_train,y_train)

print("Accuracy on train: ", accuracy_score(y_train, dt_sc_pca.predict(x_train)))

print("Accuracy on test: ", accuracy_score(y_test, dt_sc_pca.predict(x_test)))


Accuracy on train:  1.0
Accuracy on test:  0.9074074074074074
